/*
 * TAXII Client API
 * TAXII Client API (2.1)
 *
 * The version of the OpenAPI document: 0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kangov.taxii.server.web.model;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;

import io.kangov.taxii.server.ImmutableStyle;
import io.micronaut.core.annotation.Nullable;
import org.immutables.value.Value;

import java.util.*;

/**
 * The collection resource contains general information about a Collection, such as its id, a human-readable title and
 * description, an optional list of supported media_types (representing the media type of objects can be requested from
 * or added to it), and whether the TAXII Client, as authenticated, can get objects from the Collection and/or add
 * objects to it.
 */
@JsonPropertyOrder({
  Collection.JSON_PROPERTY_ID,
  Collection.JSON_PROPERTY_TITLE,
  Collection.JSON_PROPERTY_DESCRIPTION,
  Collection.JSON_PROPERTY_ALIAS,
  Collection.JSON_PROPERTY_CAN_READ,
  Collection.JSON_PROPERTY_CAN_WRITE,
  Collection.JSON_PROPERTY_MEDIA_TYPES
})
@JsonSerialize(as = CollectionImpl.class)
@JsonDeserialize(as = CollectionImpl.class)
@JsonTypeName("collection")
@Value.Immutable
@ImmutableStyle
//@Introspected
public interface Collection {

//    /**
//     * Exposes the generated builder outside this package
//     * <p>
//     * While the generated implementation (and consequently its builder) is not
//     * visible outside this package, this builder inherits and exposes all public
//     * methods defined on the generated implementation's Builder class.
//     */
////    @Introspected
//    class Builder extends CollectionImpl.Builder {}
//
//    static Collection create(UnaryOperator<Builder> spec) { return spec.apply(builder()).build(); }
//    static Collection createCollection(UnaryOperator<Builder> spec) { return create(spec); }
//    static Builder builder() { return new Builder(); }
//
//    default Collection update(UnaryOperator<Builder> builder) {
//        return builder.apply(new Builder()).build();
//    }

    String JSON_PROPERTY_ID = "id";
    String JSON_PROPERTY_TITLE = "title";
    String JSON_PROPERTY_DESCRIPTION = "description";
    String JSON_PROPERTY_ALIAS = "alias";
    String JSON_PROPERTY_CAN_READ = "can_read";
    String JSON_PROPERTY_CAN_WRITE = "can_write";
    String JSON_PROPERTY_MEDIA_TYPES = "media_types";

    /**
     * Get id
     * @return id
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public UUID getId();

    /**
     * A human-readable plain text title used to identify this Collection.
     * @return title
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_TITLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getTitle();

    /**
     * A human-readable plain text description for this Collection.
     * @return description
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_DESCRIPTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getDescription();

    /**
     * A human-readable collection name that can be used on systems to alias a collection ID. This could be used by
     * organizations that want to preconfigure a known collection of data, regardless of the underlying, collection ID
     * that is configured on a specific implementations.  If defined, the alias MUST be unique within a single api-root
     * on a single TAXII server. There is no guarantee that an alias is globally unique across api-roots or TAXII server
     * instances.
     *
     * @return alias
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_ALIAS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getAlias();

    /**
     * Indicates if the requester can read (i.e., GET) objects from this Collection. If true, users are allowed to
     * access the Get Objects, Get an Object, or Get Object Manifests endpoints for this Collection. If false, users
     * are not allowed to access these endpoints.
     *
     * @return canRead
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_CAN_READ)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getCanRead();

    /**
     * Indicates if the requester can write (i.e., POST) objects to this Collection. If true, users are allowed to
     * access the Add Objects endpoint for this Collection. If false, users are not allowed to access this endpoint.
     *
     * @return canWrite
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_CAN_WRITE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    Boolean getCanWrite();

    /**
     * A list of supported media types for Objects in this Collection. Absence of this property is equivalent to a
     * single-value list containing application/stix+json. This list MUST describe all media types that the Collection
     * can store.
     *
     * @return mediaTypes
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_MEDIA_TYPES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    List<String> getMediaTypes();

}
