/*
 * TAXII Client API
 * TAXII Client API (2.1)
 *
 * The version of the OpenAPI document: 0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kangov.taxii.server.web.model;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.*;

import io.kangov.taxii.server.ImmutableStyle;
import io.micronaut.core.annotation.Nullable;
import org.immutables.value.Value;

import java.util.Map;

/**
 * TAXII Dictionary
 */
@JsonPropertyOrder({ Dictionary.JSON_PROPERTY_DICTIONARY })
@JsonTypeName("Dictionary")
@JsonSerialize(as = DictionaryImpl.class)
@JsonDeserialize(as = DictionaryImpl.class)
//@Introspected
@Value.Immutable
@ImmutableStyle
public interface Dictionary {

//    /**
//     * Exposes the generated builder outside this package
//     * <p>
//     * While the generated implementation (and consequently its builder) is not
//     * visible outside this package, this builder inherits and exposes all public
//     * methods defined on the generated implementation's Builder class.
//     */
////    @Introspected
//    class Builder extends DictionaryImpl.Builder {}
//
//    static Dictionary create(UnaryOperator<Builder> spec) { return spec.apply(builder()).build(); }
//    static Dictionary createDictionary(UnaryOperator<Builder> spec) { return create(spec); }
//    static Builder builder() { return new Builder(); }
//
//    default Dictionary update(UnaryOperator<Builder> builder) {
//        return builder.apply(new Builder()).build();
//    }

    String JSON_PROPERTY_DICTIONARY = "dictionary";

    /**
     * Get dictionary
     * @return dictionary
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_DICTIONARY)
    @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
    public Map<String, Object> getDictionary();

}
