
micronaut:
  application:
    name: openapi-micronaut
  server:
    port: 8080
    context-path: "/"
  security:
    # authentication: bearer | cookie | session | idtoken

jackson:
  serialization:
    writeEnumsUsingToString: true
    writeDatesAsTimestamps: false
  deserialization:
    readEnumsUsingToString: true
    failOnUnknownProperties: false
    failOnInvalidSubtype: false

taxii:
  title: Taxii Server
  description: My taxii server
  contact:
    name: Darren
    email: my.domain.com
  roots:
    name: default
    description: The default api root
    domain: localhost
    path: /default


