
micronaut:
  application:
    name: taxii
  server:
    port: 8080
    context-path: "/"
  security:
    # authentication: bearer | cookie | session | idtoken

endpoints:
  health:
    details-visible: ANONYMOUS

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost/taxii`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:`taxii`}
    password: ${DB_PASSWORD:`taxii`}
    schema-generate: NONE
    dialect: POSTGRES

jackson:
  serialization:
    writeEnumsUsingToString: true
    writeDatesAsTimestamps: false
  deserialization:
    readEnumsUsingToString: true
    failOnUnknownProperties: false
    failOnInvalidSubtype: false

flyway:
  datasources:
    default:
      enabled: true

taxii:
  title: Taxii Server
  description: My taxii server
  contact:
    name: Darren
    email: my.domain.com
  roots:
    name: default
    description: The default api root
    domain: localhost
    path: /default


