/*
 * TAXII Client API
 * TAXII Client API (2.1)
 *
 * The version of the OpenAPI document: 0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kangov.taxii.server.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.micronaut.core.annotation.Nullable;
import org.immutables.value.Value;
import io.kangov.taxii.server.ImmutableStyle;

import java.util.Set;

/**
 * The collections resource is a simple wrapper around a list of collection resources.
 */
@JsonPropertyOrder({ Collections.JSON_PROPERTY_COLLECTIONS })
@JsonTypeName("collections")
@JsonSerialize(as = CollectionsImpl.class)
@JsonDeserialize(as = CollectionsImpl.class)
//@Introspected
@Value.Immutable
@ImmutableStyle
public interface Collections {

//    /**
//     * Exposes the generated builder outside this package
//     * <p>
//     * While the generated implementation (and consequently its builder) is not
//     * visible outside this package, this builder inherits and exposes all public
//     * methods defined on the generated implementation's Builder class.
//     */
////    @Introspected
//    class Builder extends CollectionsImpl.Builder {
//
//        Builder addCollection(UnaryOperator<Collection.Builder> func) {
//            addCollection(Collection.createCollection(func));
//            return this;
//        }
//
//        Builder addCollections(UnaryOperator<Collection.Builder>... funcs) {
//            addCollections(Arrays.stream(funcs).map(Collection::create).toArray(Collection[]::new));
//            return this;
//        }
//
//        Builder setCollections(Iterable<UnaryOperator<Collection.Builder>> funcs) {
//            collections(stream(funcs).map(Collection::create).toList());
//            return this;
//        }
//
//        Builder addCollections(Iterable<UnaryOperator<Collection.Builder>> funcs) {
//            addAllCollections(stream(funcs).map(Collection::create).toList());
//            return this;
//        }
//
//        private static <T> Stream<T> stream(Iterable<T> iterable) {
//            return StreamSupport.stream(iterable.spliterator(), false);
//        }
//    }
//
//    static Collections create(UnaryOperator<Builder> spec) { return spec.apply(builder()).build(); }
//    static Collections createCollections(UnaryOperator<Builder> spec) { return create(spec); }
//    static Builder builder() { return new Builder(); }
//
//    default Collections update(UnaryOperator<Builder> builder) {
//        return builder.apply(new Builder()).build();
//    }

    String JSON_PROPERTY_COLLECTIONS = "collections";


    /**
     * A list of Collections. If there are no Collections in the list, this key MUST be omitted, and the response is an
     * empty object. The collection resource is defined in section 5.2.1.
     *
     * @return collections
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_COLLECTIONS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    Set<Collection> getCollections();

}
