/*
 * TAXII Client API
 * TAXII Client API (2.1)
 *
 * The version of the OpenAPI document: 0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kangov.taxii.server.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.micronaut.core.annotation.Nullable;
import org.immutables.value.Value;
import io.kangov.taxii.server.ImmutableStyle;

/**
 * The error message is provided by TAXII Servers in the response body when returning an HTTP error status and contains
 * more information describing the error, including a human-readable title and description, an error_code and error_id,
 * and a details structure to capture further structured information about the error. All the properties are
 * application-specific, and clients shouldn&#39;t assume consistent meaning across TAXII Servers even if the codes,
 * IDs, or titles are the same.
 */
@JsonPropertyOrder({
  Error.JSON_PROPERTY_TITLE,
  Error.JSON_PROPERTY_DESCRIPTION,
  Error.JSON_PROPERTY_ERROR_ID,
  Error.JSON_PROPERTY_ERROR_CODE,
  Error.JSON_PROPERTY_HTTP_STATUS,
  Error.JSON_PROPERTY_EXTERNAL_DETAILS,
  Error.JSON_PROPERTY_DETAILS
})
@JsonTypeName("error")
@JsonSerialize(as = ErrorImpl.class)
@JsonDeserialize(as = ErrorImpl.class)
//@Introspected
@Value.Immutable
@ImmutableStyle
public interface Error {

//    /**
//     * Exposes the generated builder outside this package
//     * <p>
//     * While the generated implementation (and consequently its builder) is not
//     * visible outside this package, this builder inherits and exposes all public
//     * methods defined on the generated implementation's Builder class.
//     */
////    @Introspected
//    class Builder extends ErrorImpl.Builder {}
//
//    static Error create(UnaryOperator<Builder> spec) { return spec.apply(builder()).build(); }
//    static Error createError(UnaryOperator<Builder> spec) { return create(spec); }
//    static Builder builder() { return new Builder(); }
//
//    default Error update(UnaryOperator<Builder> builder) {
//        return builder.apply(new Builder()).build();
//    }

    String JSON_PROPERTY_TITLE = "title";
    String JSON_PROPERTY_DESCRIPTION = "description";
    String JSON_PROPERTY_ERROR_ID = "error_id";
    String JSON_PROPERTY_ERROR_CODE = "error_code";
    String JSON_PROPERTY_HTTP_STATUS = "http_status";
    String JSON_PROPERTY_EXTERNAL_DETAILS = "external_details";
    String JSON_PROPERTY_DETAILS = "details";

    /**
     * A human-readable plain text title for this error.
     * @return title
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_TITLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    String getTitle();

    /**
     * A human-readable plain text description that gives details about the error or problem that was encountered by the
     * application.
     * @return description
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_DESCRIPTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    String getDescription();

    /**
     * An identifier for this particular error instance. A TAXII Server might choose to assign each error occurrence its
     * own identifier in order to facilitate debugging.
     * @return errorId
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_ERROR_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    String getErrorId();

    /**
     * The error code for this error type. A TAXII Server might choose to assign a common error code to all errors of
     * the same type. Error codes are application-specific and not intended to be meaningful across different TAXII
     * Servers.
     * @return errorCode
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_ERROR_CODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    String getErrorCode();

    /**
     * The HTTP status code applicable to this error. If this property is provided it MUST match the HTTP status code
     * found in the HTTP header.
     * @return httpStatus
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_HTTP_STATUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    String getHttpStatus();

    /**
     * A URL that points to additional details. For example, this could be a URL pointing to a knowledge base article
     * describing the error code. Absence of this property indicates that there are no additional details.
     * @return externalDetails
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_EXTERNAL_DETAILS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    String getExternalDetails();

    /**
     * Get details
     * @return details
     **/
//    @Valid
    @Nullable
    @JsonProperty(JSON_PROPERTY_DETAILS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    Dictionary getDetails();

}
