/*
 * TAXII Client API
 * TAXII Client API (2.1)
 *
 * The version of the OpenAPI document: 0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kangov.taxii.server.model;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.micronaut.core.annotation.Nullable;
import org.immutables.value.Value;
import io.kangov.taxii.server.ImmutableStyle;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * The manifest-record type captures metadata about a single version of an object, indicated by the id property. The
 * metadata includes information such as when that version of the object was added to the Collection, the version of
 * the object itself, and the media type that this specific version of the object is available in.
 */
@JsonPropertyOrder({
  ManifestRecord.JSON_PROPERTY_ID,
  ManifestRecord.JSON_PROPERTY_DATE_ADDED,
  ManifestRecord.JSON_PROPERTY_VERSION,
  ManifestRecord.JSON_PROPERTY_MEDIA_TYPE
})
@JsonTypeName("manifest-record")
@JsonSerialize(as = ManifestRecordImpl.class)
@JsonDeserialize(as = ManifestRecordImpl.class)
//@Introspected
@Value.Immutable
@ImmutableStyle
public interface  ManifestRecord {

//    /**
//     * Exposes the generated builder outside this package
//     * <p>
//     * While the generated implementation (and consequently its builder) is not
//     * visible outside this package, this builder inherits and exposes all public
//     * methods defined on the generated implementation's Builder class.
//     */
////    @Introspected
//    class Builder extends ManifestRecordImpl.Builder {}
//
//    static ManifestRecord create(UnaryOperator<Builder> spec) { return spec.apply(builder()).build(); }
//    static ManifestRecord createManifestRecord(UnaryOperator<Builder> spec) { return create(spec); }
//    static Builder builder() { return new Builder(); }
//
//    default ManifestRecord update(UnaryOperator<Builder> builder) {
//        return builder.apply(new Builder()).build();
//    }

    String JSON_PROPERTY_ID = "id";
    String JSON_PROPERTY_DATE_ADDED = "date_added";
    String JSON_PROPERTY_VERSION = "version";
    String JSON_PROPERTY_MEDIA_TYPE = "media_type";

    /**
     * Get id
     * @return id
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    UUID getId();

    /**
     * Get dateAdded
     * @return dateAdded
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_DATE_ADDED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    OffsetDateTime getDateAdded();

    /**
     * Get version
     * @return version
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_VERSION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    OffsetDateTime getVersion();

    /**
     * A Media Type that is for STIX content such as application/stix+json;version&#x3D;2.1
     * @return mediaType
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_MEDIA_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    String getMediaType();

}
