/*
 * TAXII Client API
 * TAXII Client API (2.1)
 *
 * The version of the OpenAPI document: 0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kangov.taxii.server.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.micronaut.core.annotation.Nullable;
import org.immutables.value.Value;
import io.kangov.taxii.server.ImmutableStyle;

import java.util.Set;

/**
 * The manifest resource is a simple wrapper around a list of manifest-record items.
 */
@JsonPropertyOrder({
  Manifest.JSON_PROPERTY_MORE,
  Manifest.JSON_PROPERTY_OBJECTS
})
@JsonTypeName("manifest")
@JsonSerialize(as = ManifestImpl.class)
@JsonDeserialize(as = ManifestImpl.class)
//@Introspected
@Value.Immutable
@ImmutableStyle
public interface Manifest {

//    /**
//     * Exposes the generated builder outside this package
//     * <p>
//     * While the generated implementation (and consequently its builder) is not
//     * visible outside this package, this builder inherits and exposes all public
//     * methods defined on the generated implementation's Builder class.
//     */
////    @Introspected
//    class Builder extends ManifestImpl.Builder {}
//
//    static Manifest create(UnaryOperator<Builder> spec) { return spec.apply(builder()).build(); }
//    static Manifest createManifest(UnaryOperator<Builder> spec) { return create(spec); }
//    static Builder builder() { return new Builder(); }
//
//    default Manifest update(UnaryOperator<Builder> builder) {
//        return builder.apply(new Builder()).build();
//    }

    String JSON_PROPERTY_MORE = "more";
    String JSON_PROPERTY_OBJECTS = "objects";

    /**
     * This property identifies if there is more content available based on the search criteria. The absence of this
     * property means the value is false.
     * @return more
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_MORE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    Boolean getMore();

    /**
     * The list of manifest entries for objects returned by the request. If there are no manifest-record items in the
     * list, this key MUST be omitted, and the response is an empty object.
     * @return objects
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_OBJECTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    Set<ManifestRecord> getObjects();

}
