/*
 * TAXII Client API
 * TAXII Client API (2.1)
 *
 * The version of the OpenAPI document: 0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kangov.taxii.server.model;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.micronaut.core.annotation.Nullable;
import org.immutables.value.Value;
import io.kangov.taxii.server.ImmutableStyle;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * This type represents an object that was added, is pending, or not added to the Collection. It contains the id and
 * version of the object along with a message describing any details about its status.
 */
@JsonPropertyOrder({
  StatusDetails.JSON_PROPERTY_ID,
  StatusDetails.JSON_PROPERTY_VERSION,
  StatusDetails.JSON_PROPERTY_MESSAGE
})
@JsonTypeName("status-details")
@JsonSerialize(as = StatusDetailsImpl.class)
@JsonDeserialize(as = StatusDetailsImpl.class)
//@Introspected
@Value.Immutable
@ImmutableStyle
public interface StatusDetails {

//    /**
//     * Exposes the generated builder outside this package
//     * <p>
//     * While the generated implementation (and consequently its builder) is not
//     * visible outside this package, this builder inherits and exposes all public
//     * methods defined on the generated implementation's Builder class.
//     */
////    @Introspected
//    class Builder extends StatusDetailsImpl.Builder {}
//
//    static StatusDetails create(UnaryOperator<Builder> spec) { return spec.apply(builder()).build(); }
//    static StatusDetails createStatusDetails(UnaryOperator<Builder> spec) { return create(spec); }
//    static Builder builder() { return new Builder(); }
//
//    default StatusDetails update(UnaryOperator<Builder> builder) {
//        return builder.apply(new Builder()).build();
//    }

    String JSON_PROPERTY_ID = "id";
    String JSON_PROPERTY_VERSION = "version";
    String JSON_PROPERTY_MESSAGE = "message";

    /**
     * Get id
     * @return id
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    UUID getId();

    /**
     * Get version
     * @return version
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_VERSION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    OffsetDateTime getVersion();

    /**
     * A message indicating more information about the object being created, it's pending state, or why the object failed
     * to be created.
     * @return message
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_MESSAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    String getMessage();

}
