/*
 * TAXII Client API
 * TAXII Client API (2.1)
 *
 * The version of the OpenAPI document: 0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kangov.taxii.server.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.micronaut.core.annotation.Nullable;
import org.immutables.value.Value;
import io.kangov.taxii.server.ImmutableStyle;

import java.time.OffsetDateTime;
import java.util.Set;

/**
 * The versions resource is a simple wrapper around a list of versions.
 */
@JsonPropertyOrder({
  Versions.JSON_PROPERTY_MORE,
  Versions.JSON_PROPERTY_VERSIONS
})
@JsonTypeName("versions")
@JsonSerialize(as = VersionsImpl.class)
@JsonDeserialize(as = VersionsImpl.class)
//@Introspected
@Value.Immutable
@ImmutableStyle
public interface Versions {

//    /**
//     * Exposes the generated builder outside this package
//     * <p>
//     * While the generated implementation (and consequently its builder) is not
//     * visible outside this package, this builder inherits and exposes all public
//     * methods defined on the generated implementation's Builder class.
//     */
////    @Introspected
//    class Builder extends VersionsImpl.Builder {}
//
//    static Versions create(UnaryOperator<Builder> spec) { return spec.apply(builder()).build(); }
//    static Versions createVersions(UnaryOperator<Builder> spec) { return create(spec); }
//    static Builder builder() { return new Builder(); }
//
//    default Versions update(UnaryOperator<Builder> builder) {
//        return builder.apply(new Builder()).build();
//    }

    String JSON_PROPERTY_MORE = "more";
    String JSON_PROPERTY_VERSIONS = "versions";

    /**
     * This property identifies if there is more content available based on the search criteria. The absence of this
     * property means the value is false.
     * @return more
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_MORE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    Boolean getMore();

    /**
     * The list of object versions returned by the request. If there are no versions returned, this key MUST be omitted,
     * and the response is an empty object.
     * @return versions
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_VERSIONS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    Set<OffsetDateTime> getVersions();

}
